#! /bin/bash

System Report generated by USERNAME=$(USERNAME), TimeAndDate=$(date)

System Information

------------------

Hostname=$(hostname)

#for the OS ,to filter it further, awk has been used where -F sets the double quotes as delimiter and after setting it , the awk
#command prints the word on second place
OS=$(cat /etc/os-release | grep PRETTY_NAME | awk -F '"' '{print $2}')

Uptime=$(uptime | awk '{print$3}')  


Hardware Information

--------------------

cpu=$(lscpu | grep Model | grep -v "Model:" | sed 's/^Model name: *//')
# In the above command -v means not to include the word Model: and then sed has been used where s in single quotes means subsitution
#^ means at the very first of Model name: and * means any number of characters // means with blank. Overall it means subsititute th>

speed=$(cat /proc/cpuinfo | grep -m 1 "cpu MHz" | awk '{print $4}')
# IN the above command, -m 1 tells the grep command to stop reading after the very first match.

Ram=$(free -h | grep "Mem:" | awk '{print $2}')

disk=$(lsblk | grep disk | sed '1i NAME   MAJ:MIN RM   SIZE RO TYPE')
# In the above command 1i means insert at the first line .

video=$(sudo lshw | grep -i -A 5 display | grep -E 'product|vendor')
#Here -i means case insensitive and -A 5 means print the first five lines after the match.And the pipeline between product and 
# vendor works as or keyword.

Network Information

-------------------

FQDN=$(nslookup $(hostname) | grep -i "name:" | awk '{print $2}')

GatewayIP=$(ip route | grep default | awk '{print $3}')

DnsServer=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')


InterfaceName=$(lspci -nn | grep -i net | awk -F ']: ' '{print $2}')

IPaddress=$(ip addr show | grep -w inet | awk '{print $2}')
# -w extension of grep means matches the exact word and nothing should be attached to the word.



System Status

-------------

UsersLoggedIn=$(who | awk '{print $1}')

DiskSpace=$(echo -e "\nFileSystem FreeSpace MountedOn" ; df -h | grep -E '^/.*' | awk '{print $1,$4,$6}')
# -e after echo enables the interpretation of \ and \n means to print the words in the next line.

ProcessCount=$(ps -eo user --no-headers | sort | uniq -c |wc -l)
#In this -eo means select all the processes owned by users. Then sort command is used to sort the output in alphabetical order.
#Uniq command removes the duplicates which are next to each other and -c countes them.

LoadAverages=$(uptime | grep -o 'load average: .*' | awk '{print $3,$4,$5}')

MemoryAllocation=$(free -h | grep -o 'Mem: .*' | awk '{print $4}')

ListeningNetworkPorts=$(netstat -l | grep -w LISTEN | awk '{print$1}')

UfwRules=$(sudo ufw status numbered | awk '{print $2}')

---------------
End of Report

cat<<EOF


"System Report generated by Username = $USERNAME,   Time and date = $TimeAndDate"

System Information

------------------

Host Name = $Hostname

OS = $OS

Uptime = $Uptime


Hardware Information

--------------------

CPU = $cpu

speed = $speed

RAM = $Ram

disk = $disk

video = $video


Network Information

-------------------

FQDN = $FQDN

GatewayIP = $GatewayIP

DNS Server = $DnsServer


Interface Name = $InterfaceName

IP Address = $IPaddress


System Status

-------------

Users Logged In = $UsersLoggedIn

Disk Space = $DiskSpace

Process Count = $ProcessCount

Load Averages = $LoadAverages

Memory Allocation = $MemoryAllocation 

Listening Network Ports = $ListeningNetworkPorts

UFW Rules = $UfwRules


-------------
End of Report


EOF


